### ISSUE TITLE
Invalid package in composer.json

### ISSUE THREAD

**Issue by liamsorsby** [bbc/programmes-frontend#1073]
When attempting to require a new dependency I get an error:
```bash
:~/dev/programmes-frontend [develop]$ composer require --dev sensiolabs/security-checker

  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/bbc/gel-iconography-assets" file could not be downloaded (HTTP/1.1 404 Not Found)
```

**Comment by benolot** [comment]
Hi @liamsorsby, this is a private package which works inside the BBC's space. It is not an invalid package, just not publicly accessible.

**Comment by Bobkidbob** [comment]
The dependency cannot be downloaded as it is closed source.
