### ISSUE TITLE
Conventions for Twig / Presenters / Templates

### ISSUE THREAD

**Issue by BPScott** [bbc/programmes-frontend#26]
We've got a few things that are up for grabs, it'd be good to make some decisions and stick with them.

There's some stuff in the [Twig Coding Standards](https://twig.sensiolabs.org/doc/2.x/coding_standards.html) that are a sensible start. Notably always have a space between delimiters, e.g. `{{ foo }}`  not `{{foo}}`. (I personally preferred `{{foo}}` but if enough people do it the other way I'm happy to follow)

---

Names for Presenter arguments: camelCase or snake_case? Currently @tatitati used snake_case because that's what the old Ds2013 templates did. Amen uses camelCase. I think camelCase should be the convention we rally behind.

---

Names for Twig templates - camelCase, snake_case or hyphenated-case? Currently we use snake_case and hypenated-case in app/Resources, and camelCase in Ds2013. The [Symfony conventions](http://symfony.com/doc/current/best_practices/templates.html) suggest using snake_case. I'm personally not a big fan of snake_case but I like diverging from convention because of personal opinion even less, so I reckon following snake_case consistently would be good. This shall mean a slight change in how the template names are calculated in the base Presenter, but that's easy.

---

Names for getter function calls in twig templates: `.foo`, `.getFoo` or `.getFoo()`? Twig lets you access getters using a property-style notation (see https://twig.sensiolabs.org/doc/2.x/templates.html#variables). The above three syntaxes are equivalent.

Amen suggested using the longer `getFoo()` syntax as it is more explicit, however it looks more clunky, especially as most of our methods in presenters won't take any arguments. `.foo` looks the nicest and most compact but is there a cognitive overhead in having to work out "oh that means the getFoo method"? `.getFoo` looks weird to me and still has the clunkiness of that `get` prefix.

Alternatively could we mitigate this by not bothering with the get* prefix for methods on a Presenter? `.foo()` looks quite nice, and we could have a convention that says "if there aren't any arguments then you can drop the parens" thus having `.foo`. This is pretty much what Ruby lets you do (I've been traditionally against this as I find it unclear on if you're refering to a property or method).

~I'd be interested to see if PhpStorm is smart enough to work out the function definition stuff if we use those shorter syntaxes.~ EDIT: PhpStorm can't work definitions of any of the options so no guidance there. Taking a look into Twig's internals it looks like being explicit that you're making a function call (i.e. having parens) results in a faster code path. the difference would be pretty small but it might add up.

Related: Twig also does this shortening for is* methods, but that makes the intent harder to read IMO `.isTv()` becomes `.tv` which seems odd and `isTv` is clearer to me.

---

Opinions on a postcard, along with any other places you think we're not being consistent please @BjornTwachtmann, @tatitati, @felipeparaujo, @Tasiobg, @zoranikolic, @votemike

**Comment by BPScott** [comment]
Also once we decide we should write that up somewhere

**Comment by votemike** [comment]
I vote to stick with Twig/Symfony standards.  
My IDE has an option to reformat code to the Symfony standard and that takes care of spaces in Twig templates..
Seeing as twig templates involve a file name, I'd prefer to not have camelCase. Either StudlyCase, snake_case or hypen-ated. camelCase is fine elsewhere.

**Comment by tatitati** [comment]
In the twig doc I see everything with space. {{ foo }}, and in my opinion I think that make easier to see all the placeholders for variables.


For twig template i didn't realize, but twig doc is very clear as well:

> Best Practice
> Use lowercased snake_case for directory and template names.

For the arguments I have no preference.....

**Comment by tatitati** [comment]
Just a thought: maybe use snake_case for name templates (as the twig recommendation) and for the arguments presenter maybe is not a bad idea, in that way we can understand easily that always that appear an snake case is related to something with the presenter and its template....in that way we could say that snake_case are for template stuff.

**Comment by BPScott** [comment]
Edited the original post to add one more thing: How should we reference presenter methods from Twig template. That one is a bit thornier and would be worth having an IRL chat

**Comment by tatitati** [comment]
I really like to avoid the get, fetch...., is quite annoying. I think we should keep instead the use of "is", "has", etc for boolean operations, is more readable.

Also I like the use of brackets, to make clear that there is some processing behind (a function) doing stuff.

**Comment by votemike** [comment]
`getIsTv()`?

**Comment by tatitati** [comment]
oh nono. Just no get at all, the whole presenter is a getter actually. But if boolean use is, has, etc.

**Comment by BjornTwachtmann** [comment]
I have no particularly strong opinions on these things. We should keep template naming consistent in order to facilitate autoloading. Other than that, sticking to the thing that intellij does when you hit the format code button seems by far the easiest approach.

**Comment by felipeparaujo** [comment]
I agree with @votemike, we should stick to Twig standards. As for getters, I prefer the property-style notation.

**Comment by BPScott** [comment]
IRL team talk done. Outcomes:

* snake_case for template names - stick with the Symfony best practices
* snake_case for option names - we'll update the Amen presenters to use snake_case when we port them later.
* .thing style for presenter getters when it's a function with no arguments - this one is the most thorny Rules shall be:
  * Getters in the Presenters shall be `getFoo()` / `isBar()` / `hasBar()` etc. 
  * Use the property style method where possible.
  * If the template if the method starts with 'get' then it can be dropped.
  * Examples `getFoo()` -> `.foo`, `isBar()` -> `.isBar`, `beefcake($arg)` -> `.beefcake($arg)
