### ISSUE TITLE
Better name than ds2013

### ISSUE THREAD

**Issue by BPScott** [bbc/programmes-frontend#28]
"Design System 2013" is a bit of a a rubbish codename as pointed out by @felipeparaujo and @votemike.

I took the "mcdonalds for lunch" approach to naming this - coming up with something bad in the hope that we can come up with a better idea later. Any suggestions are welcome.

**Comment by votemike** [comment]
KFC for lunch?

**Comment by felipeparaujo** [comment]
What about Ecosystem? That would be the next level in grouping. Or maybe we just drop the 2013 and call it DesignSystem
