### ISSUE TITLE
Invalid API Endpoints for testing

### ISSUE THREAD

**Issue by Clyv** [bbc/programmes-frontend#720]
> Visit https://programmes-frontend.int.api.bbc.co.uk/whatever/your/route/is?__profile=1 (Note the double underscore). Load that at least 5 times to make sure that everything that should be cached is cached. Now visit https://programmes-frontend.int.api.bbc.co.uk/xhprof/xhprof_html/index.php.

The endpoints have (when connecting from a non-bbc environment, not sure what happens internally):

- An invalid SSL certificate
- A 404 error when visiting

**Comment by benolot** [comment]
This is only an internal (Int) url so it will not work for outside BBC Environment.
